name: ytenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.26
  - matplotlib>=3.9
  - scipy>=1.14
  - h5py>=3.12
  - pybind11>=2.13
  - yt>=4.3
  - mpi4py>=3.1
  - openmpi>=4.1
  - pytest>=8
